/**
 * Canonical system_settings keys — snake_case only.
 * All storefront/admin consumers must use these names.
 */

export const SETTING_KEYS = {
  STORE_WHATSAPP_NUMBER: 'store_whatsapp_number',
  STORE_OPENING_HOURS: 'store_opening_hours',
  STORE_OPEN_DAYS: 'store_open_days',
  STORE_SUNDAY_HOURS: 'store_sunday_hours',
  STORE_ADDRESS: 'store_address',
  STORE_NAME: 'store_name',
  PROMO_CODE: 'promo_code',
  PROMO_TITLE: 'promo_title',
  PROMO_SUBTITLE: 'promo_subtitle',
  PROMO_ACTIVE: 'promo_active',
  CAROUSEL_SPEED_MS: 'carousel_speed_ms',
  INSTAGRAM_HANDLE: 'instagram_handle',
  INSTAGRAM_URL: 'instagram_url',
  OG_IMAGE_PUBLIC_ID: 'og_image_public_id',
  ADMIN_EMAIL: 'admin_email',
  POINTS_EARN_RATE: 'points_earn_rate',
  POINTS_PER_IDR: 'points_per_idr',
  POINTS_EXPIRY_DAYS: 'points_expiry_days',
  POINTS_MIN_REDEEM: 'points_min_redeem',
  POINTS_MAX_REDEEM_PCT: 'points_max_redeem_pct',
  B2B_POINTS_MULTIPLIER: 'b2b_points_multiplier',
  PAYMENT_EXPIRY_MINUTES: 'payment_expiry_minutes',
  PAYMENT_MAX_RETRIES: 'payment_max_retries',
  FREE_SHIPPING_THRESHOLD: 'free_shipping_threshold',
  MAINTENANCE_MODE: 'maintenance_mode',
  SOFT_LAUNCH_BANNER: 'soft_launch_banner_enabled',
  SOFT_LAUNCH_WA_MESSAGE: 'soft_launch_wa_message',
  WA_DEFAULT_MESSAGE: 'wa_default_message',
  FOUNDING_YEAR: 'founding_year',
  PRICE_RANGE_MIN: 'price_range_min',
  PRICE_RANGE_MAX: 'price_range_max',
  STORE_TAGLINE: 'store_tagline',
  STORE_CITY: 'store_city',
  STORE_PROVINCE: 'store_province',
  STORE_POSTAL_CODE: 'store_postal_code',
  BITESHIP_ORIGIN_LAT: 'biteship_origin_lat',
  BITESHIP_ORIGIN_LNG: 'biteship_origin_lng',
  BITESHIP_ORIGIN_ADDRESS: 'biteship_origin_address',
  BITESHIP_ORIGIN_POSTAL_CODE: 'biteship_origin_postal_code',
  SEO_LOGO_URL: 'seo_logo_url',
  TOKOPEDIA_URL: 'tokopedia_url',
  SHOPEE_URL: 'shopee_url',
  PAYMENT_METHODS: 'payment_methods',
  RESEND_FROM_EMAIL_ORDERS: 'resend_from_email_orders',
  RESEND_FROM_EMAIL_GENERIC: 'resend_from_email_generic',
  BRAND_THEME_COLOR: 'brand_theme_color',
} as const;

export type SettingKey = (typeof SETTING_KEYS)[keyof typeof SETTING_KEYS];

/** Keys exposed by GET /api/settings/public */
export const PUBLIC_SETTING_KEYS: readonly SettingKey[] = [
  SETTING_KEYS.STORE_WHATSAPP_NUMBER,
  SETTING_KEYS.STORE_OPENING_HOURS,
  SETTING_KEYS.STORE_OPEN_DAYS,
  SETTING_KEYS.STORE_SUNDAY_HOURS,
  SETTING_KEYS.STORE_ADDRESS,
  SETTING_KEYS.STORE_NAME,
  SETTING_KEYS.STORE_TAGLINE,
  SETTING_KEYS.STORE_CITY,
  SETTING_KEYS.STORE_PROVINCE,
  SETTING_KEYS.STORE_POSTAL_CODE,
  SETTING_KEYS.INSTAGRAM_URL,
  SETTING_KEYS.INSTAGRAM_HANDLE,
  SETTING_KEYS.BITESHIP_ORIGIN_LAT,
  SETTING_KEYS.BITESHIP_ORIGIN_LNG,
  SETTING_KEYS.BITESHIP_ORIGIN_ADDRESS,
  SETTING_KEYS.BITESHIP_ORIGIN_POSTAL_CODE,
  SETTING_KEYS.SEO_LOGO_URL,
  SETTING_KEYS.TOKOPEDIA_URL,
  SETTING_KEYS.SHOPEE_URL,
  SETTING_KEYS.PAYMENT_METHODS,
  SETTING_KEYS.BRAND_THEME_COLOR,
  SETTING_KEYS.WA_DEFAULT_MESSAGE,
];

export const SETTING_GROUPS: Record<string, { label: string; keys: SettingKey[] }> = {
  store: {
    label: 'Toko',
    keys: [
      SETTING_KEYS.STORE_NAME,
      SETTING_KEYS.STORE_TAGLINE,
      SETTING_KEYS.STORE_WHATSAPP_NUMBER,
      SETTING_KEYS.STORE_ADDRESS,
      SETTING_KEYS.STORE_CITY,
      SETTING_KEYS.STORE_PROVINCE,
      SETTING_KEYS.STORE_POSTAL_CODE,
      SETTING_KEYS.STORE_OPENING_HOURS,
      SETTING_KEYS.STORE_OPEN_DAYS,
      SETTING_KEYS.STORE_SUNDAY_HOURS,
      SETTING_KEYS.INSTAGRAM_HANDLE,
      SETTING_KEYS.INSTAGRAM_URL,
      SETTING_KEYS.WA_DEFAULT_MESSAGE,
      SETTING_KEYS.SOFT_LAUNCH_BANNER,
      SETTING_KEYS.SOFT_LAUNCH_WA_MESSAGE,
      SETTING_KEYS.PAYMENT_METHODS,
    ],
  },
  promo: {
    label: 'Promo',
    keys: [
      SETTING_KEYS.PROMO_ACTIVE,
      SETTING_KEYS.PROMO_CODE,
      SETTING_KEYS.PROMO_TITLE,
      SETTING_KEYS.PROMO_SUBTITLE,
      SETTING_KEYS.CAROUSEL_SPEED_MS,
    ],
  },
  points: {
    label: 'Poin',
    keys: [
      SETTING_KEYS.POINTS_EARN_RATE,
      SETTING_KEYS.POINTS_PER_IDR,
      SETTING_KEYS.POINTS_EXPIRY_DAYS,
      SETTING_KEYS.POINTS_MIN_REDEEM,
      SETTING_KEYS.POINTS_MAX_REDEEM_PCT,
      SETTING_KEYS.B2B_POINTS_MULTIPLIER,
    ],
  },
  shipping: {
    label: 'Pengiriman',
    keys: [
      SETTING_KEYS.FREE_SHIPPING_THRESHOLD,
      SETTING_KEYS.BITESHIP_ORIGIN_LAT,
      SETTING_KEYS.BITESHIP_ORIGIN_LNG,
      SETTING_KEYS.BITESHIP_ORIGIN_ADDRESS,
      SETTING_KEYS.BITESHIP_ORIGIN_POSTAL_CODE,
    ],
  },
  seo: {
    label: 'SEO',
    keys: [
      SETTING_KEYS.OG_IMAGE_PUBLIC_ID,
      SETTING_KEYS.SEO_LOGO_URL,
      SETTING_KEYS.FOUNDING_YEAR,
      SETTING_KEYS.PRICE_RANGE_MIN,
      SETTING_KEYS.PRICE_RANGE_MAX,
      SETTING_KEYS.ADMIN_EMAIL,
      SETTING_KEYS.TOKOPEDIA_URL,
      SETTING_KEYS.SHOPEE_URL,
      SETTING_KEYS.BRAND_THEME_COLOR,
    ],
  },
  email: {
    label: 'Email',
    keys: [
      SETTING_KEYS.RESEND_FROM_EMAIL_ORDERS,
      SETTING_KEYS.RESEND_FROM_EMAIL_GENERIC,
    ],
  },
  maintenance: {
    label: 'Maintenance',
    keys: [SETTING_KEYS.MAINTENANCE_MODE],
  },
};
